### ISSUE TITLE
Build fails on Vercel

### ISSUE THREAD

**Issue by deltazero-cz** [beeinger/next-progress#2]
Local builds work fine, but when deploying on Vercel, build fails with following error:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/vercel/path0/node_modules/next-progress/node_modules/react/cjs/react.production.min.js:18:327)
    at Object.exports.useEffect (/vercel/path0/node_modules/next-progress/node_modules/react/cjs/react.production.min.js:22:364)
    at /vercel/path0/node_modules/next-progress/dist/index.js:46:11
    at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at renderPage (/vercel/path0/node_modules/next/dist/next-server/server/render.js:54:854)
    at Object.ctx.renderPage (/vercel/path0/.next/server/pages/_document.js:1099:26)
```

**Comment by beeinger** [comment]
Hi, can you show me how you implemented next-progress?
I am using next-progress on Vercel without issues
